apiVersion: apps/v1
kind: Deployment
metadata:
  name: norppalive-service
  namespace: norppalive
spec:
  template:
    spec:
      containers:
        - name: norppalive-service
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1500m
              memory: 1Gi
          volumeMounts:
            - name: yt-cookies
              mountPath: /secrets/yt
              readOnly: true
      volumes:
        - name: yt-cookies
          secret:
            secretName: norppalive-yt-cookies
            defaultMode: 0444
            items:
              - key: cookies.txt
                path: cookies.txt
