apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norppalive
resources:
  - ../../base
  - sealed-secret.yaml

images:
  - name: norppalive-service
    newName: ghcr.io/dilaz/norppalive-service
    newTag: sha-1624f5b673fddce75db8de239c456ba983719209

patches:
  - path: deployment-patch.yaml
