apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norppalive
resources:
  - ../../base
  - sealed-secret.yaml
  - sealed-yt-cookies.yaml

images:
  - name: norppalive-service
    newName: ghcr.io/dilaz/norppalive-service
    newTag: sha-2a29bb5ce7ff3aa15046a6f3d0649858432b4eb9

patches:
  - path: deployment-patch.yaml
