apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: norppalive
resources:
  - ../../base
  - sealed-secret.yaml

images:
  - name: norppalive-service
    newName: ghcr.io/dilaz/norppalive-service
    newTag: sha-196d7b40e2307ff68d82c8e85ad433455d811c66

patches:
  - path: deployment-patch.yaml
