apiVersion: v1
kind: Service
metadata:
  name: norppalive-redpanda
  annotations:
    tailscale.com/tailnet-fqdn: "norppalive-redpanda.tail7fb78e.ts.net"
spec:
  externalName: placeholder
  type: ExternalName
