name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ffmpeg and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ffmpeg \
          libavcodec-dev \
          libavdevice-dev \
          libavfilter-dev \
          libavformat-dev \
          libavutil-dev \
          libpostproc-dev \
          libswresample-dev \
          libswscale-dev \
          libclang-dev \
          pkg-config
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true,
        # Enable warnings as errors
        rustflags: "-D warnings"
    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Copy config example to config file
      run: cp config.toml.example config.toml
    - name: Run tests
      run: cargo test --verbose
