name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install ffmpeg and libavutil
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg libavutil-dev pkg-config libavformat-dev libavfilter-dev libavdevice-dev
    - name: Set PKG_CONFIG_PATH
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Copy config example to config file
      run: cp config.toml.example config.toml
    - name: Run tests
      run: cargo test --verbose
